[package]
name = "plano-repl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true, features = ["prettyprint"] }
clap = { workspace = true, features = ["derive"] }
datafusion = { workspace = true }
dirs = { workspace = true }
glob = { workspace = true }
parquet = { workspace = true, features = ["arrow"] }
plano-core = { path = "../../core" }
rds-sync = { path = "../../rds-sync" }
rustyline = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "chrono"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

