[package]
name = "plano-api"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { workspace = true }
tonic-prost = "0.14"
prost = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
tonic-prost-build = "0.14"

[package.metadata.build]
proto_root = "../../proto"
