[package]
name = "plano-core"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = { workspace = true }
datafusion = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
